<?php

/**
 * This is a Backdrop settings.ddev.php file automatically generated by DDEV.
 * #ddev-generated: Automatically generated Backdrop settings.ddev.php file.
 * DDEV manages this file and may delete or overwrite the file unless this comment is removed.
 */

$host = "ddev-ddevtest-db";
$port = 3306;
$driver = "mysql";

// If DDEV_PHP_VERSION is not set but IS_DDEV_PROJECT *is*, it means we're running (drush) on the host,
// so use the host-side bind port on docker IP
if (empty(getenv('DDEV_PHP_VERSION') && getenv('IS_DDEV_PROJECT') == "true")) {
  $host = "127.0.0.1";
  $port = 53087;
}

$database = "$driver://db:db@$host:$port/db";

$settings['hash_salt'] = '6eca762822ce42762a000dd713c4ffe4af2e2aa1a0e60bffa922435dc934074e';
